### ISSUE TITLE
iOS playback button shrunk

### ISSUE THREAD

**Issue by untoxicabs** [PopcornTimeTV/PopcornTimeTV#654]
App version: 3.2.19
iOS/tvOS version: ios 11.3.1 iphone 6s plus
I reinstalled with a fresh copy and when I play a movie all the playback buttons shrunk in horizontal view, the vertical view buttons are fine

I attached a screenshot to show the problem
Make sure these boxes are checked before submitting your issue - thanks!

**Comment by angryDuck2** [comment]
Did you use the ipa we have released or built the app from source?

**Comment by untoxicabs** [comment]
I am using a compiled version that was uploaded from appdb

**Comment by angryDuck2** [comment]
The issue could lie in the compiled version you downloaded. It could have been compiled with a beta version of Xcode which is known to have such an issue with our app

**Comment by ascarrambad** [comment]
I have the same issue: I too have an iPhone 6s Plus, the bug is present since version 3.2.5, when you updated the player UI. The bug is always present in landscape mode, though in portrait the UI is always fine. Switching between the two modes does not fix the issue. I always use your precompiled .ipa and resign it with my certificates. Seems an auto layout problem to me.
